spring:
  jwt:
    secret: videoupload_secretkey_test_infomation_code!@#

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
      location: D:\test\video\

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        use-new-id-generator-mappings: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 5000
        show_sql: false
        format_sql: false

  datasource:
    videoupload:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/video_upload?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
      username: id
      password: pw
      hikari:
        poolName: videoCP
        connectionTimeout: 10000
        maximumPoolSize: 10
        minimumIdle: 5

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: 0011
